"""
Constants for controlling taint tracking import hook behavior.

This module defines lists of modules and attributes that should be handled
specially during the taint tracking patching process to avoid conflicts,
circular imports, and other issues.
"""

# CPython modules that need special handling for taint tracking
# These modules have C extensions or special behavior that requires
# custom taint propagation through the obj_id_to_taint_origin mapping
CPYTHON_MODS = ["re"]

# Modules that are explicitly patched for taint tracking
# These modules are reloaded after the import hook is installed to
# ensure they are properly patched with taint wrappers
MODULE_WHITELIST = ["json", "re"]

# Modules that should NOT be patched for taint tracking
# This blacklist includes:
# - Core Python modules that could cause import loops or system instability
# - Standard library modules that don't need taint tracking
# - Third-party modules known to cause conflicts
MODULE_BLACKLIST = [
    "__future__",
    "__main__",
    "_thread",
    "_tkinter",
    "_io",
    "_pyio",
    "abc",
    "aifc",
    "argparse",
    "array",
    "ast",
    "asynchat",
    "asyncio",
    "asyncore",
    "atexit",
    "audioop",
    "base64",
    "bdb",
    "binascii",
    "bisect",
    "builtins",
    "bz2",
    "calendar",
    "cgi",
    "cgitb",
    "chunk",
    "cmath",
    "cmd",
    "code",
    "codecs",
    "codeop",
    "collections",
    "colorsys",
    "compileall",
    "concurrent",
    "configparser",
    "contextlib",
    "contextvars",
    "copy",
    "copyreg",
    "cProfile",
    "crypt",
    "csv",
    "ctypes",
    "curses",
    "dataclasses",
    "dill._dill",
    "datetime",
    "dbm",
    "decimal",
    "difflib",
    "dis",
    "distutils",
    "doctest",
    "email",
    "encodings",
    "ensurepip",
    "enum",
    "errno",
    "faulthandler",
    "fcntl",
    "filecmp",
    "fileinput",
    "fnmatch",
    "fractions",
    "ftplib",
    "functools",
    "gc",
    "getopt",
    "getpass",
    "gettext",
    "glob",
    "graphlib",
    "grp",
    "gzip",
    "hashlib",
    "heapq",
    "hmac",
    "html",
    "http",
    "idlelib",
    "imaplib",
    "imghdr",
    "imp",
    "importlib",
    "inspect",
    "io",
    "ipaddress",
    "itertools",
    "keyword",
    "lib2to3",
    "linecache",
    "locale",
    "logging",
    "lzma",
    "mailbox",
    "mailcap",
    "marshal",
    "math",
    "mimetypes",
    "mmap",
    "modulefinder",
    "msilib",
    "msvcrt",
    "multiprocessing",
    "netrc",
    "nis",
    "nntplib",
    "numbers",
    "operator",
    "optparse",
    "os",
    "ossaudiodev",
    "pathlib",
    "pdb",
    "pickle",
    "pickletools",
    "pipes",
    "pkgutil",
    "platform",
    "plistlib",
    "poplib",
    "posix",
    "posixpath",
    "pprint",
    "profile",
    "pstats",
    "pty",
    "pwd",
    "py_compile",
    "pyclbr",
    "pydoc",
    "queue",
    "quopri",
    "random",
    "readline",
    "reprlib",
    "resource",
    "rlcompleter",
    "runpy",
    "sched",
    "secrets",
    "select",
    "selectors",
    "shelve",
    "shlex",
    "shutil",
    "signal",
    "site",
    "smtplib",
    "sndhdr",
    "socket",
    "socketserver",
    "sqlite3",
    "ssl",
    "stat",
    "statistics",
    "string",
    "stringprep",
    "struct",
    "subprocess",
    "sunau",
    "symtable",
    "sys",
    "sysconfig",
    "syslog",
    "tabnanny",
    "tarfile",
    "telnetlib",
    "tempfile",
    "termios",
    "test",
    "textwrap",
    "threading",
    "time",
    "timeit",
    "tkinter",
    "token",
    "tokenize",
    "tomllib",
    "trace",
    "traceback",
    "tracemalloc",
    "tty",
    "turtle",
    "turtledemo",
    "types",
    "typing",
    "typing_extensions",
    "unicodedata",
    "unittest",
    "urllib",
    "uu",
    "venv",
    "warnings",
    "wave",
    "weakref",
    "webbrowser",
    "winreg",
    "winsound",
    "wsgiref",
    "xdrlib",
    "xml",
    "xmlrpc",
    "zipapp",
    "zipfile",
    "zipimport",
    "zlib",
    "zoneinfo",
    # not builtin
    "six",
    "pydantic",
]

# Specific module attributes that should NOT be patched
# Format: "module_name.attribute_name"
# These are typically internal functions that could cause issues if wrapped
MODULE_ATTR_BLACKLIST = [
    "json.load",
    "json.dump",
    "json.encoder",
    "json.decoder",
    "json.detect_encoding",
]

# Specific class methods that should NOT be patched
# Format: "ClassName.method_name"
# These are typically core methods that could break functionality if wrapped
CLS_ATTR_BLACKLIST = [
    "JSONEncoder.default",
    "JSONEncoder.decode",
    "JSONDecoder.raw_decode",
    "JSONEncoder.encode",
    "JSONEncoder.iterencode",
    "JSONDecodeError.add_note",
    "JSONDecodeError.with_traceback",
    "JSONDecoder.decode",
]
